### ISSUE TITLE
Broken link on read me file

### ISSUE THREAD

**Issue by Alvaroisit** [twmobius/Shift8#4]
Hi,

The link on the read me file is broken.

**Comment by twmobius** [comment]
Yes that's true. foriamroot.org was hacked a while ago due to a wordpress bug, and haven't found the time to get it up. I'll get the related posts in the wiki here.

Please hold :)

**Comment by twmobius** [comment]
It should be ok now. Let me know what you think!

Sorry for taking so long. :)
